# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'healthcare-code-challenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for healthcare-code-challenge
  pod 'DCDicom', '~> 0.3'

  target 'healthcare-code-challengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'healthcare-code-challengeUITests' do
    # Pods for testing
  end

end
